/** Shared enums, limits and error codes. Single source of truth for both layers. */

const GROUP_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  ARCHIVED: "ARCHIVED",
  DELETED: "DELETED",
});

const SPLIT_TYPES = Object.freeze({
  EQUAL: "EQUAL",
  EXACT: "EXACT",
  PERCENTAGE: "PERCENTAGE",
  SHARES: "SHARES",
});

/**
 * Every split type except EQUAL needs a per-participant input value. It is stored
 * as an INTEGER whose unit depends on the split type, so the no-floats rule
 * (docs/05-ALGORITHMS.md §1) holds for split inputs too:
 *
 *   EXACT       minor units      — ₹250.50 is stored as 25050
 *   PERCENTAGE  hundredths of a percent — 33.33% is stored as 3333
 *   SHARES      whole weights    — "2 shares" is stored as 2
 */
const SPLIT_VALUE_UNITS = Object.freeze({
  [SPLIT_TYPES.EXACT]: "MINOR",
  [SPLIT_TYPES.PERCENTAGE]: "CENTIPERCENT",
  [SPLIT_TYPES.SHARES]: "WEIGHT",
});

const SETTLEMENT_METHODS = Object.freeze({
  MANUAL: "MANUAL",
  // Reserved for the payments phase.
  UPI: "UPI",
  CASH: "CASH",
  CARD: "CARD",
});

const ACTIVITY_TYPES = Object.freeze({
  GROUP_CREATED: "GROUP_CREATED",
  GROUP_UPDATED: "GROUP_UPDATED",
  GROUP_ARCHIVED: "GROUP_ARCHIVED",
  MEMBER_JOINED: "MEMBER_JOINED",
  MEMBER_ADDED: "MEMBER_ADDED",
  MEMBER_RENAMED: "MEMBER_RENAMED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  EXPENSE_ADDED: "EXPENSE_ADDED",
  EXPENSE_UPDATED: "EXPENSE_UPDATED",
  EXPENSE_DELETED: "EXPENSE_DELETED",
  SETTLEMENT_RECORDED: "SETTLEMENT_RECORDED",
});

const BALANCE_STATUS = Object.freeze({
  RECEIVE: "RECEIVE",
  OWE: "OWE",
  SETTLED: "SETTLED",
});

const LIMITS = Object.freeze({
  MAX_MEMBERS_PER_GROUP: 50,
  MAX_PARTICIPANTS: 50,
  MAX_AMOUNT_MAJOR: 10_000_000,
  MAX_PAGE_SIZE: 50,
  DEFAULT_PAGE_SIZE: 20,
  INVITE_CODE_LENGTH: 16,
  GROUP_NAME_MAX: 80,
  GROUP_DESC_MAX: 500,
  MEMBER_NAME_MAX: 50,
  EXPENSE_DESC_MAX: 140,
  EXPENSE_NOTES_MAX: 500,
  SETTLEMENT_NOTE_MAX: 280,
  /** Percentages carry 2 decimals, so 100% is 10 000 centipercent. */
  PERCENT_TOTAL_CENTI: 10_000,
  /**
   * Caps `amountMinor * weight` well inside Number.MAX_SAFE_INTEGER: the largest
   * expense is 1e9 minor units and 50 participants at weight 1000 total 50 000,
   * so the widest product is 1e9 × 1000 = 1e12 — three orders of magnitude clear.
   */
  MAX_SHARE_WEIGHT: 1000,
});

const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INVALID_ID: "INVALID_ID",
  INVALID_PARTICIPANTS: "INVALID_PARTICIPANTS",
  INVALID_SPLIT: "INVALID_SPLIT",
  SELF_SETTLEMENT: "SELF_SETTLEMENT",
  NOT_A_MEMBER: "NOT_A_MEMBER",
  CREATOR_ONLY: "CREATOR_ONLY",
  GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  EXPENSE_NOT_FOUND: "EXPENSE_NOT_FOUND",
  GROUP_ARCHIVED: "GROUP_ARCHIVED",
  GROUP_DELETED: "GROUP_DELETED",
  MEMBER_HAS_ACTIVITY: "MEMBER_HAS_ACTIVITY",
  MEMBER_LIMIT_REACHED: "MEMBER_LIMIT_REACHED",
  ALREADY_CLAIMED: "ALREADY_CLAIMED",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  DUPLICATE: "DUPLICATE",
  RATE_LIMITED: "RATE_LIMITED",
  ORIGIN_NOT_ALLOWED: "ORIGIN_NOT_ALLOWED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
});

const DEFAULT_CURRENCY = "INR";

module.exports = {
  GROUP_STATUS,
  SPLIT_TYPES,
  SPLIT_VALUE_UNITS,
  SETTLEMENT_METHODS,
  ACTIVITY_TYPES,
  BALANCE_STATUS,
  LIMITS,
  ERROR_CODES,
  DEFAULT_CURRENCY,
};
