/** Shared enums, limits and error codes. Single source of truth for both layers. */

const GROUP_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  ARCHIVED: "ARCHIVED",
  DELETED: "DELETED",
});

const SPLIT_TYPES = Object.freeze({
  EQUAL: "EQUAL",
  // Reserved — the shares[] model already supports these; only the calculator
  // strategy and the UI are missing. See docs/05-ALGORITHMS.md §2.5.
  EXACT: "EXACT",
  PERCENTAGE: "PERCENTAGE",
  SHARES: "SHARES",
});

const SETTLEMENT_METHODS = Object.freeze({
  MANUAL: "MANUAL",
  // Reserved for the payments phase.
  UPI: "UPI",
  CASH: "CASH",
  CARD: "CARD",
});

const ACTIVITY_TYPES = Object.freeze({
  GROUP_CREATED: "GROUP_CREATED",
  GROUP_UPDATED: "GROUP_UPDATED",
  GROUP_ARCHIVED: "GROUP_ARCHIVED",
  MEMBER_JOINED: "MEMBER_JOINED",
  MEMBER_ADDED: "MEMBER_ADDED",
  MEMBER_RENAMED: "MEMBER_RENAMED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  EXPENSE_ADDED: "EXPENSE_ADDED",
  EXPENSE_UPDATED: "EXPENSE_UPDATED",
  EXPENSE_DELETED: "EXPENSE_DELETED",
  SETTLEMENT_RECORDED: "SETTLEMENT_RECORDED",
});

const BALANCE_STATUS = Object.freeze({
  RECEIVE: "RECEIVE",
  OWE: "OWE",
  SETTLED: "SETTLED",
});

const LIMITS = Object.freeze({
  MAX_MEMBERS_PER_GROUP: 50,
  MAX_PARTICIPANTS: 50,
  MAX_AMOUNT_MAJOR: 10_000_000,
  MAX_PAGE_SIZE: 50,
  DEFAULT_PAGE_SIZE: 20,
  INVITE_CODE_LENGTH: 16,
  GROUP_NAME_MAX: 80,
  GROUP_DESC_MAX: 500,
  MEMBER_NAME_MAX: 50,
  EXPENSE_DESC_MAX: 140,
  EXPENSE_NOTES_MAX: 500,
  SETTLEMENT_NOTE_MAX: 280,
});

const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INVALID_ID: "INVALID_ID",
  INVALID_PARTICIPANTS: "INVALID_PARTICIPANTS",
  SELF_SETTLEMENT: "SELF_SETTLEMENT",
  NOT_A_MEMBER: "NOT_A_MEMBER",
  CREATOR_ONLY: "CREATOR_ONLY",
  GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  EXPENSE_NOT_FOUND: "EXPENSE_NOT_FOUND",
  GROUP_ARCHIVED: "GROUP_ARCHIVED",
  GROUP_DELETED: "GROUP_DELETED",
  MEMBER_HAS_ACTIVITY: "MEMBER_HAS_ACTIVITY",
  MEMBER_LIMIT_REACHED: "MEMBER_LIMIT_REACHED",
  ALREADY_CLAIMED: "ALREADY_CLAIMED",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  DUPLICATE: "DUPLICATE",
  RATE_LIMITED: "RATE_LIMITED",
  ORIGIN_NOT_ALLOWED: "ORIGIN_NOT_ALLOWED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
});

const DEFAULT_CURRENCY = "INR";

module.exports = {
  GROUP_STATUS,
  SPLIT_TYPES,
  SETTLEMENT_METHODS,
  ACTIVITY_TYPES,
  BALANCE_STATUS,
  LIMITS,
  ERROR_CODES,
  DEFAULT_CURRENCY,
};
