/**
 * An allowlist sanitiser for the rich-text body of a blog post.
 *
 * ## Why this exists when only operators can write posts
 *
 * The obvious argument against sanitising here is that `requireAdmin` already
 * stands in front of every write, so the only person who can store a `<script>`
 * is someone who could deploy one anyway. That argument is true about *today's*
 * threat and wrong about the shape of the risk, for three reasons:
 *
 *  1. **The blast radius is the whole audience.** This HTML is rendered with
 *     `dangerouslySetInnerHTML` in the browser *and* injected verbatim into the
 *     pre-rendered static page (build/seoPlugin.js). A stored payload is not
 *     self-XSS; it executes for every reader who arrives from a search result.
 *  2. **The author is not always the source.** Posts get drafted in Word, pasted
 *     out of Google Docs, generated by an assistant, or lifted from another CMS.
 *     TinyMCE's paste filter runs in the browser and is trivially bypassed by
 *     anyone POSTing to the API directly — which includes an operator's own
 *     scripts. What arrives here is untrusted regardless of who sent it.
 *  3. **One compromised operator account should not become one compromised
 *     site.** An allowlist turns "attacker who phishes an admin" into "attacker
 *     who can write articles", which is a materially smaller incident.
 *
 * The cost is stated plainly: this refuses markup that a trusted author might
 * legitimately want — embeds, custom widgets, inline styles beyond a fixed set.
 * That is the intended trade. Widening it is a deliberate edit to the lists
 * below, not something a post can negotiate at runtime.
 *
 * ## Why the parser is hand-written and not a dependency
 *
 * `sanitize-html` and DOMPurify-on-jsdom are both better-tested than this file,
 * and either would be the right call if the input were arbitrary. Two things
 * argue for keeping it local: the allowlist here is *narrow* — a fixed set of
 * document tags with no SVG, no MathML, no namespaces and no template content,
 * which removes almost every category of parser-differential bug those libraries
 * exist to absorb — and adding a transitive dependency tree to a server that
 * currently has fifteen direct dependencies is its own kind of risk.
 *
 * The honest limitation: this is a tokeniser, not a spec-compliant HTML5 parser.
 * It does not model foreign content, and it does not attempt to. It is safe
 * because of what it *removes* — every tag not on the list is dropped along with
 * its content when it is dangerous, every attribute not on the list is dropped
 * unconditionally, and every URL is re-parsed rather than pattern-matched.
 */

/**
 * Elements a post body may contain.
 *
 * Notable absences, each deliberate:
 *
 * - `<script>`, `<style>`, `<iframe>`, `<object>`, `<embed>`, `<form>`,
 *   `<input>`: the obvious execution and credential-harvesting vectors.
 * - `<link>`, `<meta>`, `<base>`: head elements. `<base>` in particular rewrites
 *   every relative URL on the page, which silently repoints the site's own
 *   navigation at another host.
 * - `<svg>`: carries its own scripting surface (`<script>` inside SVG, event
 *   handlers on shapes, `<use href>` pulling in external documents) and is not
 *   something an article body needs.
 */
const ALLOWED_TAGS = new Set([
  // Headings. h1 is absent: the page's single h1 is the post title, rendered by
  // the template. A second one in the body is an SEO defect, not a style choice.
  "h2", "h3", "h4", "h5", "h6",
  "p", "br", "hr", "div", "span",
  "strong", "b", "em", "i", "u", "s", "strike", "del", "ins", "mark", "sub", "sup", "small",
  "blockquote", "q", "cite", "abbr",
  "ul", "ol", "li", "dl", "dt", "dd",
  "a", "img", "figure", "figcaption", "picture", "source",
  "table", "thead", "tbody", "tfoot", "tr", "th", "td", "caption", "colgroup", "col",
  "pre", "code", "kbd", "samp", "var",
  // Semantic sectioning TinyMCE will not emit on its own but a pasted document
  // might, and which carry no behaviour.
  "section", "article", "aside", "header", "footer", "nav", "main", "time",
]);

/**
 * Tags whose *content* is discarded along with the tag.
 *
 * For everything else, unwrapping is right — an unknown `<center>` should leave
 * its text behind. For these, the text **is** the payload: dropping `<script>`
 * while keeping its body would paste raw JavaScript into the article.
 */
const VOID_CONTENT_TAGS = new Set([
  "script", "style", "iframe", "object", "embed", "noscript", "template",
  "svg", "math", "form", "textarea", "select", "option", "button", "input",
  "title", "head", "base", "meta", "link",
]);

/** Elements with no closing tag, so the stack must not wait for one. */
const SELF_CLOSING = new Set(["br", "hr", "img", "col", "source", "wbr"]);

/**
 * Attributes allowed on any element, plus the per-element additions below.
 *
 * `class` is here and `style` is not. Classes resolve against a stylesheet this
 * project controls, so the worst a bad one does is look wrong. Inline styles are
 * an open-ended language: `position: fixed` over the whole viewport is a
 * clickjacking primitive, and historically `expression()` and `url(javascript:)`
 * were code execution. A fixed set of alignment styles is handled separately.
 */
const GLOBAL_ATTRS = new Set(["class", "id", "title", "dir", "lang", "role"]);

const TAG_ATTRS = {
  a: new Set(["href", "target", "rel", "download", "hreflang"]),
  img: new Set(["src", "alt", "width", "height", "loading", "decoding", "srcset", "sizes"]),
  source: new Set(["src", "srcset", "sizes", "type", "media"]),
  time: new Set(["datetime"]),
  td: new Set(["colspan", "rowspan", "headers", "scope"]),
  th: new Set(["colspan", "rowspan", "headers", "scope", "abbr"]),
  col: new Set(["span"]),
  colgroup: new Set(["span"]),
  ol: new Set(["start", "reversed", "type"]),
  blockquote: new Set(["cite"]),
  q: new Set(["cite"]),
  del: new Set(["cite", "datetime"]),
  ins: new Set(["cite", "datetime"]),
  abbr: new Set(["title"]),
};

/** Attributes that hold a URL and must therefore be parsed, not pattern-matched. */
const URL_ATTRS = new Set(["href", "src", "cite", "srcset"]);

/**
 * Schemes a URL in this document may use.
 *
 * `javascript:` and `vbscript:` are the classic ones. `data:` is excluded too —
 * `data:text/html` is a same-origin document in some contexts, and a legitimate
 * article has no reason to inline a base64 image when there is an upload
 * endpoint that produces a cacheable file with a real URL.
 */
const ALLOWED_SCHEMES = new Set(["http:", "https:", "mailto:", "tel:"]);

/**
 * The subset of inline styling worth preserving, since `style` is dropped whole.
 *
 * TinyMCE writes `text-align` for the alignment buttons, and losing it silently
 * un-centres every image an author has centred. Only these exact declarations
 * survive, with values matched against a literal list — never a pattern that
 * could admit a `url(...)`.
 */
const ALLOWED_STYLES = {
  "text-align": new Set(["left", "right", "center", "justify"]),
};

const decodeEntities = (value) =>
  value
    .replace(/&#x([0-9a-f]+);?/gi, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);?/g, (_, dec) => String.fromCodePoint(Number(dec)))
    .replace(/&quot;?/gi, '"')
    .replace(/&apos;?/gi, "'")
    .replace(/&lt;?/gi, "<")
    .replace(/&gt;?/gi, ">")
    // Ampersand last, so "&amp;#x6a;" does not decode twice into a "j".
    .replace(/&amp;?/gi, "&");

const escapeAttr = (value) =>
  String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

/**
 * A URL, or null if it is not one this document may point at.
 *
 * Parsed with `new URL` rather than tested with a regex. Blocklist regexes lose
 * to encoding — `java&#x09;script:`, `\tjavascript:`, `JaVaScRiPt&colon;` and a
 * NUL byte in the middle have all defeated one in production somewhere. Entities
 * and control characters are stripped first, then the scheme is read by the
 * parser and compared against an allowlist, so anything unparseable or unknown
 * fails closed.
 *
 * Relative URLs are resolved against a throwaway base purely to *classify* them;
 * the original string is what gets written back, so `/blog/other-post` stays
 * relative in the output.
 */
const safeUrl = (raw) => {
  // Control characters — including the tab, newline and NUL used to split a
  // scheme — are removed before anything looks at the string.
  const cleaned = decodeEntities(String(raw)).replace(/[\u0000-\u0020\u007F-\u00A0\u2028\u2029]/g, "").trim();
  if (!cleaned) return null;

  // A bare fragment or query is same-document and has no scheme to check.
  if (cleaned.startsWith("#") || cleaned.startsWith("?")) return cleaned;

  // Protocol-relative ("//evil.com") is treated as https, which is what a
  // browser would do on this site, so it is judged as the absolute URL it is.
  const candidate = cleaned.startsWith("//") ? `https:${cleaned}` : cleaned;

  let parsed;
  try {
    parsed = new URL(candidate, "https://sanitizer.invalid");
  } catch {
    return null;
  }

  if (!ALLOWED_SCHEMES.has(parsed.protocol)) return null;

  return cleaned;
};

/**
 * `srcset` is a comma-separated list of URLs with descriptors. Each entry is
 * checked independently; one bad entry drops that entry rather than the
 * attribute, because a responsive image with three sources and one typo should
 * still render the other two.
 */
const safeSrcset = (raw) => {
  const entries = String(raw)
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean)
    .map((entry) => {
      const [url, ...descriptors] = entry.split(/\s+/);
      const checked = safeUrl(url);
      return checked ? [checked, ...descriptors].join(" ") : null;
    })
    .filter(Boolean);

  return entries.length ? entries.join(", ") : null;
};

const safeStyle = (raw) => {
  const kept = String(raw)
    .split(";")
    .map((declaration) => {
      const [property, ...rest] = declaration.split(":");
      const name = (property || "").trim().toLowerCase();
      const value = rest.join(":").trim().toLowerCase();
      const allowed = ALLOWED_STYLES[name];
      return allowed && allowed.has(value) ? `${name}: ${value}` : null;
    })
    .filter(Boolean);

  return kept.length ? kept.join("; ") : null;
};

/** `a="b" c='d' e=f`, tolerating unquoted and valueless attributes. */
const ATTR_PATTERN = /([a-zA-Z_:][-a-zA-Z0-9_:.]*)\s*(?:=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+)))?/g;

const sanitizeAttributes = (tag, rawAttrs) => {
  const out = [];
  let match;

  ATTR_PATTERN.lastIndex = 0;
  while ((match = ATTR_PATTERN.exec(rawAttrs)) !== null) {
    const name = match[1].toLowerCase();
    const value = match[2] ?? match[3] ?? match[4] ?? "";

    /**
     * Every `on*` attribute, refused as a family rather than enumerated.
     *
     * A list of known handler names goes stale the moment a browser ships a new
     * event, and the allowlist below would already drop them — this is belt and
     * braces for the one case where a handler name collides with something
     * allowed. Same for anything carrying a namespace separator, which is how
     * `xlink:href` smuggles a URL past a check that only looked at `href`.
     */
    if (name.startsWith("on") || name.includes(":")) continue;

    if (name === "style") {
      const style = safeStyle(value);
      if (style) out.push(`style="${escapeAttr(style)}"`);
      continue;
    }

    const allowed = GLOBAL_ATTRS.has(name) || TAG_ATTRS[tag]?.has(name);
    if (!allowed) continue;

    if (URL_ATTRS.has(name)) {
      const url = name === "srcset" ? safeSrcset(value) : safeUrl(value);
      if (!url) continue;
      out.push(`${name}="${escapeAttr(url)}"`);
      continue;
    }

    out.push(value === "" ? name : `${name}="${escapeAttr(value)}"`);
  }

  return out;
};

/**
 * Links that leave the site get `rel="noopener noreferrer"`, and links that stay
 * get any `target` removed.
 *
 * `noopener` is a security fix — without it the opened page can navigate this
 * one via `window.opener`, which is a phishing primitive. It is applied here
 * rather than trusted from the author because it must hold for every external
 * link, including ones pasted from elsewhere with a `rel` of their own.
 *
 * `nofollow` is deliberately **not** added. These are editorially chosen links
 * in an article; blanket-nofollowing them signals to search engines that the
 * site does not stand behind anything it cites, which is both untrue and bad for
 * the outbound-link signal. Mark paid links per-post if that ever becomes a
 * thing.
 */
const finaliseAnchor = (attrs) => {
  const href = attrs.find((attr) => attr.startsWith('href="'));
  if (!href) return attrs;

  // `//evil.com` counts as external too. It is protocol-relative, so a browser
  // resolves it to another origin exactly as an absolute URL would — matching
  // only on `http(s)://` here would leave that case without `noopener`.
  const isExternal = /^href="(?:https?:)?\/\//i.test(href);
  const withoutRel = attrs.filter((attr) => !attr.startsWith('rel="') && !attr.startsWith('target="'));

  if (!isExternal) return withoutRel;

  return [...withoutRel, 'target="_blank"', 'rel="noopener noreferrer"'];
};

/**
 * Images are lazy-loaded and async-decoded unless the author said otherwise.
 *
 * This is a Core Web Vitals measure, not a cosmetic one: an article with eight
 * screenshots blocks its own Largest Contentful Paint on images nobody has
 * scrolled to yet, and LCP is a ranking input. Added server-side so it holds in
 * the pre-rendered HTML a crawler measures, not only in the React render.
 */
const finaliseImage = (attrs) => {
  const has = (name) => attrs.some((attr) => attr === name || attr.startsWith(`${name}="`));
  const out = [...attrs];
  if (!has("loading")) out.push('loading="lazy"');
  if (!has("decoding")) out.push('decoding="async"');
  // An <img> with no alt is an accessibility failure and a missed keyword slot.
  // Empty rather than invented: alt="" marks it decorative, which is at least
  // honest, whereas guessing a description would put words in the author's mouth.
  if (!has("alt")) out.push('alt=""');
  return out;
};

const TOKEN = /<!--[\s\S]*?-->|<\/?([a-zA-Z][a-zA-Z0-9-]*)((?:[^>"']|"[^"]*"|'[^']*')*)>/g;

/**
 * Sanitise a rich-text fragment.
 *
 * Returns HTML that is safe to insert into a document. Unknown-but-harmless tags
 * are unwrapped (their children survive), dangerous ones are removed whole, and
 * text is passed through untouched — it is already inert, and re-escaping it
 * would double-encode every ampersand an author typed.
 */
const sanitizeHtml = (input) => {
  const html = String(input ?? "");
  if (!html) return "";

  const out = [];
  /** Open allowed elements, so a stray `</div>` cannot close something it did not open. */
  const stack = [];
  /**
   * Depth inside a dropped subtree. A counter rather than a boolean because
   * `<script><script>` is legal input and one `</script>` must not resume output.
   */
  let suppressed = 0;
  let suppressTag = null;
  let cursor = 0;
  let match;

  const pushText = (text) => {
    if (suppressed === 0 && text) out.push(text);
  };

  TOKEN.lastIndex = 0;
  while ((match = TOKEN.exec(html)) !== null) {
    pushText(html.slice(cursor, match.index));
    cursor = TOKEN.lastIndex;

    // Comments are dropped entirely. They are invisible to readers and a known
    // place to hide conditional-comment markup that some parsers execute.
    if (match[0].startsWith("<!--")) continue;

    const tag = (match[1] || "").toLowerCase();
    const isClosing = match[0][1] === "/";

    if (suppressed > 0) {
      // Inside a dropped subtree: only the matching tag moves the counter.
      if (tag === suppressTag) {
        if (isClosing) {
          suppressed -= 1;
          if (suppressed === 0) suppressTag = null;
        } else if (!SELF_CLOSING.has(tag) && !match[0].endsWith("/>")) {
          suppressed += 1;
        }
      }
      continue;
    }

    if (VOID_CONTENT_TAGS.has(tag)) {
      if (!isClosing && !match[0].endsWith("/>")) {
        suppressed = 1;
        suppressTag = tag;
      }
      continue;
    }

    if (!ALLOWED_TAGS.has(tag)) {
      // Unwrapped, not dropped: an unrecognised wrapper around a paragraph
      // should cost the wrapper, not the paragraph.
      continue;
    }

    if (isClosing) {
      const index = stack.lastIndexOf(tag);
      // A close with no matching open is noise from a malformed paste.
      if (index === -1) continue;
      // Implicitly close anything left open inside it, innermost first, so the
      // output is balanced even when the input was not.
      while (stack.length > index) out.push(`</${stack.pop()}>`);
      continue;
    }

    let attrs = sanitizeAttributes(tag, match[2] || "");
    if (tag === "a") attrs = finaliseAnchor(attrs);
    if (tag === "img") attrs = finaliseImage(attrs);

    const rendered = attrs.length ? `<${tag} ${attrs.join(" ")}>` : `<${tag}>`;

    if (SELF_CLOSING.has(tag)) {
      out.push(rendered);
    } else {
      out.push(rendered);
      stack.push(tag);
    }
  }

  pushText(html.slice(cursor));

  // Whatever the author left open, this closes.
  while (stack.length) out.push(`</${stack.pop()}>`);

  return out.join("");
};

/**
 * The article as words, for reading time and for the excerpt fallback.
 *
 * Runs on sanitised HTML, so there is no markup left that could survive tag
 * removal — this is a presentation helper, never a security boundary.
 */
const htmlToText = (html) =>
  decodeEntities(
    String(html ?? "")
      // Block boundaries become spaces, or "end.<p>Start" reads as one word.
      .replace(/<(?:br|\/p|\/div|\/li|\/h[1-6]|\/tr)[^>]*>/gi, " ")
      .replace(/<[^>]*>/g, "")
  )
    .replace(/\s+/g, " ")
    .trim();

module.exports = { sanitizeHtml, htmlToText, safeUrl };
